### ISSUE TITLE
Have each course appearing on the schedule page with a different color 

### ISSUE THREAD

**Issue by mukulikadey** [mukulikadey/SOEN341-Group1#101]
Each course that a student user takes, when it appears on the schedule page, they all have the same color. This should be fixed, so that each user can differentiate their classes by corresponding a unique color to each course. 
Hours: 2

**Comment by j-suguma** [comment]
If you can can just vote with the corresponding symbol of which one you like. Then again the color will change depending on the course but just in general which one prefer :) @mukulikadey  @Gabbell  @samratdebroy  @jameelbrochu @rekandiah @coreylevine @svelupillai 
Option 1: thumbs up 👍 
![image](https://cloud.githubusercontent.com/assets/25251601/24074664/7b365238-0be3-11e7-8d2a-e7eccb00124f.png)

Option2: 100 sign 💯 
![image](https://cloud.githubusercontent.com/assets/25251601/24074694/e1f96870-0be3-11e7-83f1-11567f52de47.png)

Option 3: heart ❤️ 
![image](https://cloud.githubusercontent.com/assets/25251601/24074732/b81d868e-0be4-11e7-8cbf-f20925f3066a.png)

Option 4: tada 🎉 
![image](https://cloud.githubusercontent.com/assets/25251601/24074818/6d6d2b92-0be6-11e7-97cd-b535d0e83aaf.png)

**Comment by rekandiah** [comment]
Tada 🎉

**Comment by samratdebroy** [comment]
@rekandiah if you look the top right of @j-suguma 's comment, you will see a smiley face icon. hovering over that icon will prompt you to "Add your reaction". I think Jonathan wanted us to vote using the reactions, it's not really an issue though given we aren't many people.

**Comment by j-suguma** [comment]
The 4th option was chosen based on popularity vote so the issue can now be closed
