### ISSUE TITLE
Remove subscriber from course sections when a user switches from one section to another for a course

### ISSUE THREAD

**Issue by samratdebroy** [mukulikadey/SOEN341-Group1#102]
Parent Issue: #81
Hours: 2 hours

**Comment by samratdebroy** [comment]
With @svelupillai 's fix, not only is the code simplified and cleaner, but the subscribers are removed even when switching between lecture sections. The gif below shows the proper functioning of the code where the user is removed as a subscriber when he/she switches out of a lecture section for another in a given course.

![changesections_senegafix](https://cloud.githubusercontent.com/assets/10346242/24074845/f7da4ef4-0be6-11e7-999d-17c00613a415.gif)

**Comment by samratdebroy** [comment]
2 hours

**Comment by svelupillai** [comment]
Hours: 0.5
