### ISSUE TITLE
The data generated in the timetable node is wrong

### ISSUE THREAD

**Issue by Gabbell** [mukulikadey/SOEN341-Group1#104]
Based on the COEN346 node, the data generated in the timetable seems to be wrong. 

![pasted image at 2017_03_20 05_22 pm](https://cloud.githubusercontent.com/assets/10086598/24122811/ae84ef44-0d93-11e7-85c9-93f62ebce253.png)

There is basically a class every day. I think it is the same number of total class in the semester but they just happend every day. Tues is set to "Y" and Wed to "N".

**Comment by Gabbell** [comment]
This does not seem to be true for most courses. We should re-evaluate its priority or close it completely.

**Comment by mukulikadey** [comment]
Since this issue is only occurring for only this course (COEN-346), and it is not present with most other courses, this doesn't seem to be of relevant priority at this moment. Therefore, this issue can be closed.
