### ISSUE TITLE
As a user, when I add a course and click on a section, I should see that section darkened to see that I made a choice

### ISSUE THREAD

**Issue by mukulikadey** [mukulikadey/SOEN341-Group1#107]
Risk: Low
Priority: Low 
Points: 5 
Hours: 5 hours

Acceptance criteria: Given that the user is on the homepage, when I click on "Add a course" button, I will see a list of sections to choose from. After I make that selection, that section should be darkened to see that I made a choice.

**Comment by samratdebroy** [comment]
Should we maybe also see the names of the sections to which a user is subscribed in low-opacity font right below the course name? So on my homepage for example, I would see "LEC: N" "TUT: NX" "LAB: NX-J" in smaller font under say "COEN342".

**Comment by mukulikadey** [comment]
This user story can be closed.  Now when the user searches for a course, the sections are separated into lectures, tutorials and/or labs. When the user clicks on a section, the section is darkened to indicate the user's choice. This issue was committed to the designWebsite branch for which a PR was created. The PR was reviewed and tested. Since it successfully passed, this can now be closed.

**Comment by svelupillai** [comment]
hours: 6
