### ISSUE TITLE
Testing for Frontend/Backend 

### ISSUE THREAD

**Issue by mukulikadey** [mukulikadey/SOEN341-Group1#108]
Hours: 6 hours

**Comment by rekandiah** [comment]
![1](https://cloud.githubusercontent.com/assets/15826622/24461741/14d76604-1470-11e7-9925-9ae5abfb6239.jpg)
![2](https://cloud.githubusercontent.com/assets/15826622/24461744/17110204-1470-11e7-9e42-0efa40fc3c72.jpg)
![3](https://cloud.githubusercontent.com/assets/15826622/24461746/18c1942e-1470-11e7-9510-3ad8d416b80d.jpg)

**Comment by coreylevine** [comment]
Hours: 20

**Comment by rekandiah** [comment]
Hours Spent: 8

**Comment by rekandiah** [comment]
Sprint 5: Test Cases Results for automated tests
[Sprint 5-Test Case Results.pdf](https://github.com/mukulikadey/SOEN341-Group1/files/908575/Sprint.5-Test.Case.Results.pdf)
 
Hours Spent creating new test cases and evaluating old ones: 2

**Comment by mukulikadey** [comment]
Hours: 3

**Comment by coreylevine** [comment]
Hours: 15
