### ISSUE TITLE
Acceptance Cases 

### ISSUE THREAD

**Issue by mukulikadey** [mukulikadey/SOEN341-Group1#109]
These are the acceptance cases for Sprints 1, 2, 3, 4, and 5

**Comment by mukulikadey** [comment]
![image](https://cloud.githubusercontent.com/assets/25259429/24131044/9707711e-0dc2-11e7-8fc7-9f0366759dec.png)

**Comment by mukulikadey** [comment]
![image](https://cloud.githubusercontent.com/assets/25259429/24131089/d74f1de4-0dc2-11e7-94ad-7c38174106b0.png)
![image](https://cloud.githubusercontent.com/assets/25259429/24131135/2170c076-0dc3-11e7-9ca7-129c4b1a6b44.png)

**Comment by mukulikadey** [comment]
![image](https://cloud.githubusercontent.com/assets/25259429/24131226/a52fedec-0dc3-11e7-9ef0-cc5fab266734.png)
![image](https://cloud.githubusercontent.com/assets/25259429/24131243/ba6c7676-0dc3-11e7-9f89-5e42aeb83d7a.png)

**Comment by mukulikadey** [comment]
![image](https://cloud.githubusercontent.com/assets/25259429/24131277/f7c0cc8e-0dc3-11e7-8dd4-b73a3318f1e9.png)
![image](https://cloud.githubusercontent.com/assets/25259429/24131289/06176c2a-0dc4-11e7-9a08-4044ab6af492.png)

**Comment by mukulikadey** [comment]
![image](https://cloud.githubusercontent.com/assets/25259429/24131343/75e11a6a-0dc4-11e7-8d02-c71718d562d4.png)
![image](https://cloud.githubusercontent.com/assets/25259429/24131349/874f5d98-0dc4-11e7-9a4f-0b041626c6e9.png)

**Comment by rekandiah** [comment]
For Sprint 5: This is what we expect to test for sprint 5 given are expected specifications and requirement for the upcoming sprint.

**Comment by rekandiah** [comment]
Hours Spent: 4

**Comment by mukulikadey** [comment]
Hours helping: 4
