### ISSUE TITLE
Display a popover box in the navigation bar, where the user will see the recent changes to their courses

### ISSUE THREAD

**Issue by mukulikadey** [mukulikadey/SOEN341-Group1#122]
Parent Issue: #120 
Hours: 2 hours

**Comment by j-suguma** [comment]
You need to do npm install react-toastr-redux --save to use toastr

**Comment by jameelbrochu** [comment]
Instead of a transparent box on homepage, going to try to make it a popover in the navigation menu like this https://react-bootstrap.github.io/components.html#popovers

**Comment by mukulikadey** [comment]
Hours worked: 2 hours

**Comment by j-suguma** [comment]
Tim: 3 hours

**Comment by jameelbrochu** [comment]
Time: 3 hours
