### ISSUE TITLE
On the schedule page, change the sign in status of google export, to colored buttons

### ISSUE THREAD

**Issue by mukulikadey** [mukulikadey/SOEN341-Group1#123]
Hours: 2 hours

**Comment by jameelbrochu** [comment]
add `margin-bottom: 10px` to the status icon

**Comment by j-suguma** [comment]
Hows this then 
![image](https://cloud.githubusercontent.com/assets/25251601/24375059/fd756fd6-1304-11e7-9f42-bef6095e7522.png)

**Comment by jameelbrochu** [comment]
Better!

**Comment by j-suguma** [comment]
Okay then ill close the issue now

**Comment by j-suguma** [comment]
Okay it is now aligned so i will close the issue

**Comment by jameelbrochu** [comment]
Time: 30 mins
