### ISSUE TITLE
General design improvements to website 

### ISSUE THREAD

**Issue by mukulikadey** [mukulikadey/SOEN341-Group1#124]
Hours: 20

- [x] Remove Forum Button
- [x] If user has no courses added, user should receive appropriate message on schedule page. 
- ~~If user tries to add a course that's already in the list, user should receive an alert message about it~~
- [x] Improve the design of the CUSE bar/navigation bar at the top of the website
- [x] When user removes a course, the user should receive an alert message to confirm the removal
- [x] Change background of website to match with the navigation bar
- [x] Add different background for schedule page that still matches with the rest of the site
- [x] Add alert on notification icon to notify user they have unread notifications
- [x] Change notification alert icon on navbar to a counter with number of unread notifications
- [x] Modify bootstrap alert styling around site for error messages and successful messages
- [x]  Improve design of profile page and of login/register page

**Comment by mukulikadey** [comment]
@jameelbrochu @j-suguma This is how it looks like. User can click on link and it will direct them to homepage. 
![image](https://cloud.githubusercontent.com/assets/25259429/24334708/531f3e58-123d-11e7-8fad-616d7bce8768.png)

**Comment by j-suguma** [comment]
Ohh alright, it looks good 😄

**Comment by jameelbrochu** [comment]
~~If user tries to add a course that's already in the list, user should receive an alert message about it~~
After discussion with team, we decided that since course sections will be added to homepage, having this alert was reductant.

**Comment by jameelbrochu** [comment]
Modified navigation bar to remove the drop-down and add the logo.
![image](https://cloud.githubusercontent.com/assets/16848284/24576037/58c99f08-1682-11e7-9095-3d4866c49695.png)

**Comment by j-suguma** [comment]
Hmmm i really like the addition of the logo 😄 and the yellow icons but maybe if we make the navbar disappear or like blend into the background picture it would look better. That way it does not look like two pieces, but one general flow on the web page

**Comment by jameelbrochu** [comment]
Here's how it looks now with the changed background image and modified navbar.
![image](https://cloud.githubusercontent.com/assets/16848284/24582351/247c46d6-16fc-11e7-934f-965470d5ecdf.png)

**Comment by j-suguma** [comment]
This is how it looks currently, cant see the "waves" well since its a screenshot 
![image](https://cloud.githubusercontent.com/assets/25251601/24583491/a7350aa0-1719-11e7-9ecd-aee373f36142.png)

**Comment by jameelbrochu** [comment]
Updated look...
![image](https://cloud.githubusercontent.com/assets/16848284/24590836/4c2ad3b6-17c2-11e7-8fbb-0cd72558d118.png)
![image](https://cloud.githubusercontent.com/assets/16848284/24590844/67673ec6-17c2-11e7-9f6a-32cddf1e127a.png)
![image](https://cloud.githubusercontent.com/assets/16848284/24590835/40ecfba0-17c2-11e7-9e5d-d44a5eabecb5.png)
Still need to work on navbar on schedule page

**Comment by j-suguma** [comment]
This is how the profile page looks now:
![image](https://cloud.githubusercontent.com/assets/25251601/24590900/9c176ea6-17c3-11e7-90a7-10b996f65088.png)

**Comment by jameelbrochu** [comment]
Updated add courses component.
![image](https://cloud.githubusercontent.com/assets/16848284/24670864/b31c3246-193d-11e7-8b3c-87f80ae04e8b.png)

**Comment by rekandiah** [comment]
hours spent: 3

**Comment by jameelbrochu** [comment]
@j-suguma  🎉🎉  https://gyazo.com/43db109eedcf1aedd4126f942de97232

**Comment by jameelbrochu** [comment]
Changed notification alert to counter.
Before:
![image](https://cloud.githubusercontent.com/assets/16848284/24837842/e375bdc4-1d0a-11e7-90ee-404c0beb4c05.png)
After:
![image](https://cloud.githubusercontent.com/assets/16848284/24837801/f00b79f8-1d09-11e7-8305-e3b6deeb9db6.png)
And this is what it should look like with the correct dates:
![image](https://cloud.githubusercontent.com/assets/16848284/24837848/058b0770-1d0b-11e7-8a04-b8f30707ca4b.png)

**Comment by Gabbell** [comment]
This is what it looks like now. I removed the seconds.

![image](https://cloud.githubusercontent.com/assets/10086598/24838571/484131fe-1d18-11e7-803e-b3c813382c40.png)

**Comment by j-suguma** [comment]
So this is how it looks now, just have to click the link to see a GIF
https://gyazo.com/75d292e4d9d0450f3e06bf5161aa0aaf

**Comment by svelupillai** [comment]
hours: 3

**Comment by mukulikadey** [comment]
Hours: 4

**Comment by j-suguma** [comment]
Hours: 14.5

**Comment by jameelbrochu** [comment]
Time: 5 hours
