### ISSUE TITLE
Every time a TA/Prof edits a course description, store a notification in the path /notifications/[user UID]/[List of unique keys]/Notification_object on Firebase for EVERY subscriber of the edited section. 

### ISSUE THREAD

**Issue by samratdebroy** [mukulikadey/SOEN341-Group1#127]
Parent Issue: #120
Hours: 4 hours

**Comment by samratdebroy** [comment]
Each notification object should include, email of person making the edit, course details (course section, time/date of edited class, location) and new description (and maybe old description). It would also be wise to pass the key of the parent object holding the notification_object as it is randomly generated and can't be deduced later on.

**Note: It would be highly advised to make sure we use Firebase's .push(value) method to push these notifications to the /notifications/[user UID]/ path as Firebase will automatically create the unique key under which the passed value will be stored. This key will be generated as a timestamp so that our list will be ordered for us as a function of latest->oldest notifications and hence, there are many advantages to it (ex: when we only want to display the *x* latest notification).**

**Comment by samratdebroy** [comment]
Can confirm @Gabbell 's changes work. In the image below, we can see a new path under notifications/<user uid> that holds a list of recent notifications sent to the user. These notifications are updated for every subscriber of an edited course. The image below depicts an example of a user with notifications ( each notification has its own unique ID) .

![image](https://cloud.githubusercontent.com/assets/10346242/24816800/268c6284-1ba8-11e7-853d-7123bb4a57be.png)

**Comment by Gabbell** [comment]
Hours: 4
