### ISSUE TITLE
When a user logs in, download all the recent notification objects and listen for changes using the full Redux pipeline.

### ISSUE THREAD

**Issue by samratdebroy** [mukulikadey/SOEN341-Group1#128]
Parent Issue: #120
Hours: 5 hours

**Comment by samratdebroy** [comment]
We are most definitely going to want to structure this so that we listen to changes in real-time instead of just when we refresh the page. As such, Firebase's .on should be used instead of .once so as to use an active listener that responds to changes in the database. This also implies some significant changes in the way the action-creator is designed. Refer to the getUserCourses() function in firebase_actions.js for an insight into how to implement this.

**Comment by svelupillai** [comment]
hours:5
