### ISSUE TITLE
Push the notifications to the transparent box as clickable cards (Front-End)

### ISSUE THREAD

**Issue by samratdebroy** [mukulikadey/SOEN341-Group1#129]
Parent Issue: #120
Hours: 4 hours

**Comment by samratdebroy** [comment]
So I was thinking that clicking the cards should either display more details and/or display an "_x_" button that can be pressed so as to remove the notification from the box.

**Comment by mukulikadey** [comment]
@jameelbrochu @j-suguma Guys it looks like this now: 
![image](https://cloud.githubusercontent.com/assets/25259429/24436000/a643aa54-1406-11e7-89c2-45bfd0c9b948.png)

It's not as appealing as the previous one, but now instead of being hard coded, the cards are displayed through a function.

**Comment by mukulikadey** [comment]
Hour: 5

**Comment by j-suguma** [comment]
Time: 3

**Comment by jameelbrochu** [comment]
Time: 3 hours
