### ISSUE TITLE
As a user, I should be able to login to the website

### ISSUE THREAD

**Issue by mukulikadey** [mukulikadey/SOEN341-Group1#13]

**Comment by Gabbell** [comment]
This is pretty much ready. We only need to merge environmentTest to the master.

**Comment by j-suguma** [comment]
Still need to address the other issues for this sprint

**Comment by coreylevine** [comment]
User can successfully enter the website after logging in.

- A user can login to the website given they are registered with a valid email and password, or if they have       a google account.

- After successfully logging in the user will be directed to the schedule exporter page.

- After logging out, the user will be redirected to the login page.

**Comment by j-suguma** [comment]
Hours: 4
