### ISSUE TITLE
Ensure the professor can also edit the class descriptions even if their email isn't in the course section's white-list.

### ISSUE THREAD

**Issue by samratdebroy** [mukulikadey/SOEN341-Group1#133]
Parent Issue: #106
Hours: 1 hour

**Comment by samratdebroy** [comment]
Small thing we didn't include in our logic last sprint. Currently only users whose email appears in a course section's white list can edit the description of classes. Of course, the professor's email shouldn't need to be added to the white list for him/her to edit the class. They should be given the right as soon as their email matches with the one associated to the course section's professor's email.

**Comment by samratdebroy** [comment]
Alternatively, this issue could also be resolved by ensuring the the professor's email is indeed added to the white-list the first time the course section is added by a user.

**Comment by svelupillai** [comment]
The prof can now edit the description field, so I am closing the issue.
Number of hours: 0.5
