### ISSUE TITLE
Manually add a few dummy courses to the database with the emails of our developers as "professor email" so as to be able to test the professor's functionalities. 

### ISSUE THREAD

**Issue by samratdebroy** [mukulikadey/SOEN341-Group1#134]
Parent Issue: #106
Hours: 3 hours

**Comment by samratdebroy** [comment]
These dummy courses should completely emulate the real ones already on Firebase in order to ensure the accuracy of the tests. This means adding all the fields we see for a course section under the /course/[course section] path as well as adding it under the /section/[course number]/[course section] path.

Specifically, the "Email" field under /course/[course section] path should contain the email of one of our developers.

**Comment by coreylevine** [comment]
Each developer in the team has been added as profs to their own section of the fictional ENGR999 course. Therefore the path ENGR999XX where XX is the person's initials (capitalized) has the corresponding dev as professor. Do to the tedious nature of manually adding all the details for each of the eight developpers on Firebase, Keyboard and Mouse Macros were written using AutoHotKey format for Windows in .ahk files. One macro was created to add Section (Windows Key + CTRL + S ) and another for Lecture sections (Windows Key + CTRL + L ). The gif below demonstrates the automated inputs carried out by the course lecture macro. This helped significantly speed up the process and allows us to easily add new "courses" in the future.

![automateaddingcoursemacro](https://cloud.githubusercontent.com/assets/25109164/24531171/ea3ada64-1584-11e7-8564-cb750a5b1f3a.gif)

**Comment by coreylevine** [comment]
Macros for adding new section in the /sections/ENGR999/XX path where XX are initials
[sections.txt](https://github.com/mukulikadey/SOEN341-Group1/files/884118/sections.txt)

**Comment by coreylevine** [comment]
Macro for adding new lecture sections in the /course/ENGR999XX/ path where XX are the initials:
[LectureSections.txt](https://github.com/mukulikadey/SOEN341-Group1/files/884121/LectureSections.txt)

**Comment by coreylevine** [comment]
In order for a user to add a new section in the /course/ENGR999XX/ path, they must first add an arbitrary field so that the node is not empty after navigating their browser URL to the aforementioned path. Then they must hover over the "+" sign next to the node's name and then press the hotkey Windows Key + CTRL + L. Finally, they simply need to answer the prompts and the rest is automated by the Macro. The user NEEDS to make sure to not move the mouse during the macro's execution or risk succumbing to unwanted behaviour.

**Comment by coreylevine** [comment]
Hours worked: 3

**Comment by samratdebroy** [comment]
Hours spent helping: 2 hours
