### ISSUE TITLE
Make sure the user is signed out of the Google API when they signed out from the website

### ISSUE THREAD

**Issue by Gabbell** [mukulikadey/SOEN341-Group1#135]
As of right now, the user will stay signed in the Google API even though they signed out from the website. This makes it so that when you log out from a Gmail account and connect with a normal email account, you're still connected to the Google API and can still export to your calendar. This is unintended.

**Comment by mukulikadey** [comment]
This was a duplicate issue to #125 . Therefore this was removed.
