### ISSUE TITLE
Research and Implement Static Analysis Tool

### ISSUE THREAD

**Issue by rekandiah** [mukulikadey/SOEN341-Group1#139]
Parent Issue: #108 

Hours: 5

**Comment by rekandiah** [comment]
We can maybe try out PMD. @coreylevine 

https://pmd.github.io/

**Comment by rekandiah** [comment]
We used JSHint as our static analysis tool. 2 of our main javascript files were tested and fixed. These files are app_tests.js (our unit tests file) and the firebase.js file.

Below are the following status reports given by JSHint:
[firebase.pdf](https://github.com/mukulikadey/SOEN341-Group1/files/907916/firebase.pdf)
[unittests.pdf](https://github.com/mukulikadey/SOEN341-Group1/files/907917/unittests.pdf)

**Comment by coreylevine** [comment]
Hours: 2
