### ISSUE TITLE
Dropdown for add course still shows N/A when you select a section

### ISSUE THREAD

**Issue by j-suguma** [mukulikadey/SOEN341-Group1#150]
Hours: 1 Hour

Given that I add a course on the home page, the drop down still shows N/A instead of changing to the selected section

However in the box of "Classes you are taking" the section gets updated.
Here is a small clip of the bug:
https://gyazo.com/c27e663d71138961963ec3d584aee65f

**Comment by jameelbrochu** [comment]
Tested it out and it works. Dropdowns for add courses and add tas are cleared as defaults and when the section is selected for add courses, it changes on the course list.

**Comment by svelupillai** [comment]
Hours: 0.5
