### ISSUE TITLE
Make a note about using providers for log in

### ISSUE THREAD

**Issue by j-suguma** [mukulikadey/SOEN341-Group1#16]
Notify the users that if they are registering for the first time with google, they should redirect themselves to the login page and just login with google which will prompt them to connect their gmail to the website

**Comment by Gabbell** [comment]
We should just remove the Google button on the register page and put it only on the login page.

**Comment by j-suguma** [comment]
Okay sounds good i'll close the issue

**Comment by Gabbell** [comment]
Hours: 1
