### ISSUE TITLE
Find a website name

### ISSUE THREAD

**Issue by samratdebroy** [mukulikadey/SOEN341-Group1#18]
- [x] Choose website name
       Hours: 1 hour

**Comment by Gabbell** [comment]
Concordia University Schedule Exporter (C.U.S.E.)

**Comment by rekandiah** [comment]
![sample1](https://cloud.githubusercontent.com/assets/15826622/22526055/bde0fff8-e897-11e6-9eb8-d02ab429dce9.png)

sample logo

**Comment by mukulikadey** [comment]
This issue can be closed. We have already decided on a website name.

**Comment by coreylevine** [comment]
Hours: 1
