### ISSUE TITLE
Look up how to implement automated testing for React.js and Firebase

### ISSUE THREAD

**Issue by samratdebroy** [mukulikadey/SOEN341-Group1#21]
Going to have to test:
- Log-in process
- Database interaction with Firebase
- Google API
- Concordia API (If we're ever given access)
- Whatever other classes get implemented in the code

**Comment by mukulikadey** [comment]
This issue can be closed. Included it as a sub-task to issue #27.

**Comment by rekandiah** [comment]
Hours Spent: 2

**Comment by coreylevine** [comment]
Hours: 10
