### ISSUE TITLE
As a user, I should see the list of courses on the home page -- Points: 8 -- Risk: High --

### ISSUE THREAD

**Issue by samratdebroy** [mukulikadey/SOEN341-Group1#22]
On the schedule page, the user should be able to see their assigned list of courses. 

- [x] We need to figure out the way the data will be structured in the Firebase database ( i.e. figure out what type of data each node level on the data tree will contain)
- [x] Make sure data related to at least one section of one course is added to the Firebase database. If we can only add one course, it should be a SOEN course (preferably SOEN 341) 
- [x] If we are given access to the Concordia API, we should figure out how to import the data into Firebase. We need to make a list of data to request from IITS for a Minimum Viable Product. (ex: Course timetables, instructors, section numbers,etc.)

**Comment by Gabbell** [comment]
Draft model of the database: https://codeshare.io/soen341-1

It is easier to do it in JSON and import it to Firebase than doing it directly on Firebase. They do not allow to add a child to a parent if it is already added to the database.

**Comment by samratdebroy** [comment]
Hours Spent : 12

**Comment by svelupillai** [comment]
Hours: 8

**Comment by Gabbell** [comment]
Hours: 10
