### ISSUE TITLE
Perform automated tests for the login page -- Points: 8 -- Risk: High --

### ISSUE THREAD

**Issue by mukulikadey** [mukulikadey/SOEN341-Group1#27]
- [x] Research testing environment for react.js for backend and frontend
- [x] Have test cases ready for Login Page and Home Page
- [x] Show TravisCl works and has available empty tests (As instructed from lecture slides - “devops”)

**Comment by mukulikadey** [comment]
The tests have been completed for the login and homepage.

**Comment by coreylevine** [comment]
Hours worked: 15

**Comment by rekandiah** [comment]
Hours Spent: 10

**Comment by coreylevine** [comment]
Hours: 2
