### ISSUE TITLE
As a user, after logging in, I should see the homepage -- Points: 1 -- Risk: Low --

### ISSUE THREAD

**Issue by j-suguma** [mukulikadey/SOEN341-Group1#33]
The home page of the website is the first page that the user is directed to after logging in. 

- [x] Direct to home page instead of schedule page after login
- [x] The homepage should have buttons that allows user to access the Schedule and Profile Pages.

**Comment by mukulikadey** [comment]
This issue #33 can be closed. The user is now directed to the home page after login. The home page includes buttons that directs user to schedule and profile pages.

**Comment by jameelbrochu** [comment]
All tasks completed. User now sees homepage after login.

**Comment by mukulikadey** [comment]
Hour: 5

**Comment by j-suguma** [comment]
Hour: 3

**Comment by jameelbrochu** [comment]
Time: 2 hours
