### ISSUE TITLE
The first time a course section receives a subscriber, a timetable needs to be created that contains a list of each individual class dates and an empty description field.

### ISSUE THREAD

**Issue by Gabbell** [mukulikadey/SOEN341-Group1#35]
- [x] Make a function that can read the data in a course section's data node (for tutorial and lecture sections ) and create a JSON timetable object from it. @svelupillai 
- [x] When the newly added section is a lab section, the timetable creation function should read all the separate lab data nodes and create one single timetable from the separate firebase paths. @samratdebroy
- [x] Make sure the timetable creation function is called when a subscriber is added for the first time to a course and never called again on that course section. Also connect this function to the Firebase database so that the data is added online and is available to all. @Gabbell 
- [x] (Optional) Add logic in the timetable creation function so that it skips march break and doesn't add any classes to it. @samratdebroy

Parent Issue: #66 
Hours: 12

**Comment by mukulikadey** [comment]
This issue will be moved to Sprint 3, because we are going to use the excel sheet with the list of courses that we received from Concordia's IT department, which will require us to change the structure of our database.

**Comment by samratdebroy** [comment]
Can confirm that all timetables, including those for lab sections are being properly created! As can be seen in the image below, ELEC311 section HL-X has six sessions and the timetable managed to get all six individual dates.

![image](https://cloud.githubusercontent.com/assets/10346242/23640071/3d9fe052-02b9-11e7-906b-cb96b99b4f0a.png)

**Comment by samratdebroy** [comment]
I just tested Gabriel's code for adding subscribers and I can confirm it works properly. Updates Firebase just as we expect it by adding a subscriber node in the added course section.

![image](https://cloud.githubusercontent.com/assets/10346242/23692392/30e99b26-039c-11e7-96f2-3d00f37b5e4a.png)

**Comment by samratdebroy** [comment]
Just tested pushing Timetables asynchronously to Firebase! Everything seems to work for pushing timetables to course sections.

![timetabletofirebase](https://cloud.githubusercontent.com/assets/10346242/23709812/a35034f8-03e8-11e7-868a-a46a44f904d1.gif)

**Comment by samratdebroy** [comment]
I just added logic so that we don't schedule classes during holidays or the reading week. I only found Feb 20 - Feb 26 ( Reading week) and April 14 - April 17 ( Easter Weekend and End of classes) as dates during the Winter semester where no classes are given. The data was acquired from Concordia's official Academic Calendar. Tested on Firebase and working.

**Comment by samratdebroy** [comment]
Hours Spent: 8

**Comment by Gabbell** [comment]
Hours: 3

**Comment by svelupillai** [comment]
hours: 4
