### ISSUE TITLE
As a user, the first page I see of the website, includes the Login and Registration options -- Points: 1 -- Risk: Low --

### ISSUE THREAD

**Issue by coreylevine** [mukulikadey/SOEN341-Group1#36]
When the user is not logged in, the first thing they see is the Login and Registration options. If they are logged in, then they should be directed to the home page.

**Comment by mukulikadey** [comment]
This issue #36 can be closed. The first page the user sees on the website, includes the Login and Registration options.

**Comment by svelupillai** [comment]
hours: 1
