### ISSUE TITLE
As a user, I should see an empty static calendar on the schedule page -- Points: 5 -- Risk: High --

### ISSUE THREAD

**Issue by mukulikadey** [mukulikadey/SOEN341-Group1#50]
There should be a static calendar component, so that this calendar can later be dynamic and populated with the course details.

**Comment by mukulikadey** [comment]
This issue can be closed. The user can see a static calendar on the schedule page.

**Comment by mukulikadey** [comment]
Hours helping: 2

**Comment by j-suguma** [comment]
Hours: 5

**Comment by jameelbrochu** [comment]
Time: 4 hours
