### ISSUE TITLE
If the course exists, add the student as a subscriber to that course, else display a message that the course doesn't exist. Then we have to make sure that the course course isn't already in the student's course array.

### ISSUE THREAD

**Issue by mukulikadey** [mukulikadey/SOEN341-Group1#62]
- [x] Print out the available sections (as buttons) when user enters a course number in the "add a course" textbox @Gabbell 
- [x] Make the courselist update the database in real time (without refreshing a page) @samratdebroy
- [x] connect the "Add a course" button to the database so that courses are added to the user's CourseArray  and seen in real time on their homepage @samratdebroy
- [x] Add error checks associated to the "Add a course" (ex: when user tries to add a course that doesn't exist, when a user adds a section they already subscribed to, etc. ) @svelupillai 
- [x] Add the user as a subscriber to the course sections they add using the "Add a course" button. @Gabbell 

Parent Issue: #66 
Hours: 12

**Comment by mukulikadey** [comment]
Discussion: For more details, please refer to slack conversation ( ) which can be found in the Wiki. 

Problem1: When we print out "sections", it seems to print a Promise. If we try to console log sections in firebase.js before returning it, we get a proper array. So if we try to print out sections.payload in index_home, it gives "undefined". 
Solution1: If the requests have something to do with each other, then we leave them in the same reducer. For example, for updating information, in this case we use the same reducer, because we want our props to hold the updated info. 

Problem2: So now we have an onclick function for the sections and a user decides to add a specific section to their course list. Then to push that info to the database, would we make a new reducer or just use the database.js one since it's already dealing with the users/uid/coursearray data?
Solution2: The databse.js is used to get data from the /users root, so when we push things into the same root, we will use the same reducer.

**Comment by Gabbell** [comment]
Doing this.props.sections.sections seems redundant. Maybe we should refactor it?

**Comment by svelupillai** [comment]
Ya sure, the other part is sections.loaded which is a boolean that is true if the reducer is loaded. We don't really need it. This.props.sections could just be an array of the sections

**Comment by samratdebroy** [comment]
I just tested Gabriel's code for adding subscribers and I can confirm it works properly. Updates Firebase just as we expect it by adding a subscriber node in the added course section. This subtask can therefore be closed!

![image](https://cloud.githubusercontent.com/assets/10346242/23692392/30e99b26-039c-11e7-96f2-3d00f37b5e4a.png)

**Comment by samratdebroy** [comment]
Hours Spent: 2

**Comment by svelupillai** [comment]
Hours: 2
