### ISSUE TITLE
As a user, I should be able to add courses

### ISSUE THREAD

**Issue by mukulikadey** [mukulikadey/SOEN341-Group1#66]
Agile Specifications: 
Points: 8
Risk: High

- [x] After the "Add Courses" button is clicked, a text area appears, where the user chooses their courses.
      Hours: 3 hours
- [x] If the course exists, add the student as a subscriber to that course, else display a message that the course doesn't exist. Then we have to make sure that the course course isn't already in the student's course array. 
     Hours: 12 hours
- [x] The first time a course section receives a subscriber, a timetable needs to be created that contains a list of each individual class dates and an empty description field. 
     Hours: 12 hours
- [x] Create backend and frontend test cases and do regression testing. 
      Hours: 3 hours

Acceptance Criteria: As a user, after clicking on the "Add Courses" button, I will see a text area where I can choose my classes for my schedule. If the course exists, then I will be subscribed to the class. If the course doesn't exist, then I will see a message that tells me that this course doesn't exist. Also, when I click a course to add to my schedule, and I am already subscribed to it, then I will see a display with the appropriate message. 

Mock up of what the add courses functionality could potentially look like:
<img width="238" alt="addcoursesmockup" src="https://cloud.githubusercontent.com/assets/25239116/23089801/ad67e10a-f55d-11e6-9570-2cd180a0ab16.PNG">

**Comment by samratdebroy** [comment]
Made a small update to the database in the "sections" node.

**Comment by samratdebroy** [comment]
Flowchart to add a class to the user's courseArray and subscribe them to specific sections

![add a class](https://cloud.githubusercontent.com/assets/10346242/23277916/a914fc08-f9dd-11e6-94c0-9ac96371dabd.png)

**Comment by rekandiah** [comment]
@svelupillai  @samratdebroy  @Gabbell 
Bug Report: 
Given that I'm logged in as user1 and add my courses
And I log out
When I login as user 2
Then the courses that were added with user 1 still appear on the homepage
When I refresh the page
Then user2 finally sees their courses on their homepage

**Comment by mukulikadey** [comment]
This story can be closed. All subtasks/issues to this story are completed.

**Comment by samratdebroy** [comment]
Hours spent: 12

**Comment by Gabbell** [comment]
Hours: 8

**Comment by svelupillai** [comment]
hours: 7
