### ISSUE TITLE
As a user, I should be able to export my classes to my google calendar

### ISSUE THREAD

**Issue by rekandiah** [mukulikadey/SOEN341-Group1#71]
Agile Specification:
Points: 8
Risk: High
Priority: High

- [x] Add a button for: exporting to google calendar @Gabbell 
      Hours: 7 hours 
- [x] Push the events of the student's calendar to their google calendar. Every time the student exports, their previous calendar will be deleted and will be replaced by the new one, in its entirety. @Gabbell 
      Hours: 10 hours
- [x] Regression testing for frontend/backend testing @rekandiah @coreylevine 
      Hours: 6 hours 

Acceptance criteria: On the schedule page, the user will see a drop down menu allowing the user to choose if he/she wants to export their schedule to their google calendar, to jpeg, or pdf format.

**Comment by Gabbell** [comment]
Since we cannot retrieve the oAuth object returned by signing in with Google into Firebase, we have to find another way. One simple way to fix this would be to use a different token for the Google Calendar API effectively making the user sign in twice into two different platforms.

**Comment by Gabbell** [comment]
Events are now properly pushed to the user's Google calendar BUT the data in userEvents seems to be wrong in some way.

**Comment by mukulikadey** [comment]
This user story can be closed. The user can successfully export their schedule's events to their google calendar.

**Comment by Gabbell** [comment]
Hours: 20
