### ISSUE TITLE
Convert the calendar from static to dynamic

### ISSUE THREAD

**Issue by mukulikadey** [mukulikadey/SOEN341-Group1#72]
Parent Issue: #61 
Hours: 8

**Comment by j-suguma** [comment]
@mukulikadey  @jameelbrochu so this is how it looks 
![image](https://cloud.githubusercontent.com/assets/25251601/23097996/33244302-f611-11e6-9ca2-0f7c7eea1fd0.png)

![image](https://cloud.githubusercontent.com/assets/25251601/23098002/44d58868-f611-11e6-9cd7-0b9866c1f8bf.png)

![image](https://cloud.githubusercontent.com/assets/25251601/23098007/59127660-f611-11e6-94d9-e807c447760b.png)

**Comment by j-suguma** [comment]
For it to compile,after pulling the branch everyone needs to install two npm packages
npm install react-big-calendar --save
npm install moment --save

**Comment by mukulikadey** [comment]
The calendar was converted from static to dynamic. Therefore, this issue was closed.

**Comment by j-suguma** [comment]
Research time spent: 6 hours
Looked up various other templates before finding react-big calendar
Other schedule templates: dxhtml Scheduler, jqwidgets Scheduler, full Calendar
Templates stated above did not implement well with our project thus had to keep on searching

**Comment by jameelbrochu** [comment]
Time: 3 hours
