### ISSUE TITLE
Configure the layout to have weekly view on schedule

### ISSUE THREAD

**Issue by mukulikadey** [mukulikadey/SOEN341-Group1#73]
Parent Issue: #61 
Hours: 5 Hours

**Comment by j-suguma** [comment]
Hours worked: 5

**Comment by mukulikadey** [comment]
@mukulikadey  @jameelbrochu so this is how it looks 
![image](https://cloud.githubusercontent.com/assets/25251601/23097996/33244302-f611-11e6-9ca2-0f7c7eea1fd0.png)

![image](https://cloud.githubusercontent.com/assets/25251601/23098002/44d58868-f611-11e6-9cd7-0b9866c1f8bf.png)

![image](https://cloud.githubusercontent.com/assets/25251601/23098007/59127660-f611-11e6-94d9-e807c447760b.png)

**Comment by mukulikadey** [comment]
The calendar now has a weekly view. Therefore, this issue can now be closed.

**Comment by jameelbrochu** [comment]
Time: 1 hour
