### ISSUE TITLE
Add events to calendar on schedule page

### ISSUE THREAD

**Issue by mukulikadey** [mukulikadey/SOEN341-Group1#74]
Parent issue: #61 
Hours: 5

**Comment by mukulikadey** [comment]
The events (student's courses) are now populated on the dynamic calendar. This issue can therefore be closed. 
Hours worked: 5

**Comment by jameelbrochu** [comment]
Time: 6 hours
Missing:
- Fix the first loading issue when accessing the schedule
- Remove the half-hours in the weekly calendar view
- Shorten the height of the calendar
- Try to figure out problem with timeslots={2} versus timeslots={4} (causing a problem with position of events on calendar)

**Comment by j-suguma** [comment]
Time: 2 hours
