### ISSUE TITLE
Perform frontend and backend testing

### ISSUE THREAD

**Issue by mukulikadey** [mukulikadey/SOEN341-Group1#76]
Parent Issues: #66 and #61 
Hours: 6

- [x] Front-end testing assigned to: @rekandiah 
- [x] Back-end testing assigned to: @coreylevine

**Comment by mukulikadey** [comment]
Testing is completed. It successfully passes on Travis.

**Comment by coreylevine** [comment]
Hours worked: 8

**Comment by rekandiah** [comment]
Hours spent:10
