### ISSUE TITLE
Design the overall website 

### ISSUE THREAD

**Issue by mukulikadey** [mukulikadey/SOEN341-Group1#80]
- Design the overall look of the website to make it more inviting to users. 
- Regression Testing
Hours: 4
Assigned to: @mukulikadey

**Comment by mukulikadey** [comment]
Hours worked: 2.5 Hours

**Comment by j-suguma** [comment]
Looks good I liked it follows the same background as the homepage

**Comment by mukulikadey** [comment]
The design of the website is completed for the sprint. This issue can therefore be closed.

**Comment by jameelbrochu** [comment]
Time: 1 hour
