### ISSUE TITLE
Design and Architecture diagram 

### ISSUE THREAD

**Issue by mukulikadey** [mukulikadey/SOEN341-Group1#83]
![341architecture_s3](https://cloud.githubusercontent.com/assets/25259429/23667810/1d1486ac-032d-11e7-9fbc-26268e7f5c9e.JPG)

**Comment by coreylevine** [comment]
This chart makes it a lot easier to visualize our repository.

**Comment by coreylevine** [comment]
I just want to clarify that the real-time database API means that when a change is made to the database on our website, the change is automatically put into the firebase database, without the user having to save the information, right?

**Comment by mukulikadey** [comment]
@coreylevine Yes exactly, since firebase is a real-time database, so what you described above is exactly what happens.

**Comment by mukulikadey** [comment]
This issue can now be closed. The architecture diagram is displayed above. We used the Model View Controller (MVC) architectural pattern.

**Comment by samratdebroy** [comment]
The fact that it's realtime means that a user can see changes made in the database without having to refresh their page. This allows us to have a dynamic website that can react to asynchronous events such as specific data in our Firebase databse changing at any time.

**Comment by mukulikadey** [comment]
Hour: 3
