### ISSUE TITLE
Remove subscriber from the course node

### ISSUE THREAD

**Issue by mukulikadey** [mukulikadey/SOEN341-Group1#87]
Parent Issue: #81 
Hours: 4 hours

**Comment by svelupillai** [comment]
When the user decides to remove a course, that course's lecture section, tutorial section and lab section (if the exist) are iterated over to obtain the section path. This section path is needed to remove the user from the section's subscriber list. Each section path's subscriber object gets the user removed from it and then the new modified object is used to set the section's subscriber's object.
