### ISSUE TITLE
Make the button of google export aesthetically aligned with the schedule page

### ISSUE THREAD

**Issue by mukulikadey** [mukulikadey/SOEN341-Group1#88]
Hours: 2 hours

**Comment by j-suguma** [comment]
This is how it looks, also applies for #123
![image](https://cloud.githubusercontent.com/assets/25251601/24374801/330d6c76-1304-11e7-9c78-be4d8f418716.png)

**Comment by mukulikadey** [comment]
Really nice! I like how you changed the color of the button and the size of the status sign is perfect! Thanks Jonathan! :)

**Comment by jameelbrochu** [comment]
add margin-bottom: 10px to the status icon

**Comment by j-suguma** [comment]
Okay ill close then issue now

**Comment by jameelbrochu** [comment]
Time: 30 mins
