### ISSUE TITLE
Push the events of the student's calendar to their google calendar. Every time the student exports, their previous calendar will be deleted and will be replaced by the new one, in its entirety.

### ISSUE THREAD

**Issue by mukulikadey** [mukulikadey/SOEN341-Group1#89]
Parent Issue: #71 
Hours: 10 hours

**Comment by Gabbell** [comment]
The web app will first look for a calendar with the summary (title) "CUSE". If it finds it, it deletes it. Then, it creates a whole new calendar and pushes new events into it. This is to update all events in the Google Calendar in case their dates or description were changed.

**Comment by mukulikadey** [comment]
This issue can be closed. When the user logged in with a gmail account, clicks on the button "Export to calendar", the user's courses are displayed on the user's google calendar.
