### ISSUE TITLE
On the first load, the courses don't appear on the schedule, but the userEvents array is never empty.

### ISSUE THREAD

**Issue by mukulikadey** [mukulikadey/SOEN341-Group1#95]
Example:
Given I am on the Home Page
When I navigate to Schedule Page
Then I want to see all my added courses on the schedule
But instead I see an empty schedule
When I switch views (week/day or month)
Then my added courses appear on the schedule

**Comment by mukulikadey** [comment]
This bug has been fixed. When the student user goes on the schedule page, the courses appear on the schedule on the first load. Therefore, this issue can now be closed.

**Comment by rekandiah** [comment]
hours spent: 5
