### ISSUE TITLE
When the user clicks on an event/class on schedule, there should be a modal that allows you to add description

### ISSUE THREAD

**Issue by mukulikadey** [mukulikadey/SOEN341-Group1#97]
Hours: 5 
Parent Issue: #65

**Comment by mukulikadey** [comment]
This is how it currently looks like:
![image](https://cloud.githubusercontent.com/assets/25259429/23930274/9512da80-0901-11e7-9ad7-b0f6d1284c17.png)

**Comment by mukulikadey** [comment]
Make sure to do: **npm install sweetalert** to get all the appropriate files.

**Comment by j-suguma** [comment]
Looks good for now but just need to add
**npm install sweetalert --save** 
the save is so it gets stored in our project
Ill try working on how to to let the user add a description

**Comment by j-suguma** [comment]
Now it looks like this 
![image](https://cloud.githubusercontent.com/assets/25251601/23956241/894810a0-0972-11e7-9cd9-7afd4ec37f15.png)
![image](https://cloud.githubusercontent.com/assets/25251601/23956250/91170ca0-0972-11e7-9d4b-e659a1d4fb17.png)

**Comment by jameelbrochu** [comment]
@j-suguma this is what the pop looks like now. I was also able to add the section and component (lec/lab/tut) in the calendar view but it changes the colours so I removed them. Tomorrow, we can look at maybe changing the colour theme so we can re-add them or figure out another way so that it doesn't affect the colours of each course.
![image](https://cloud.githubusercontent.com/assets/16848284/24126766/30b8e44a-0da6-11e7-89f8-382a7ff5561a.png)

**Comment by j-suguma** [comment]
@jameelbrochu i fixed it so that the type of class and the section appear without changing the color, is it good?
![image](https://cloud.githubusercontent.com/assets/25251601/24127940/e5f9a9ea-0dae-11e7-927c-35ecf8d3beed.png)

**Comment by jameelbrochu** [comment]
I think we should change the components to full names (Lecture, Tutorial, Laboratory) by creating if statements from the info from the database like we did for the TBA course times. And then have the "Laboratory" become "Lab" in the popup so it takes up less space. And remove the brackets on the calendar view.

**Comment by j-suguma** [comment]
Alright how does it look now? I made the changes you requested
![image](https://cloud.githubusercontent.com/assets/25251601/24128973/d316ef84-0db5-11e7-8c0a-444f7d3b7f15.png)

only problem is if the course time slot is too small cant see all the details

**Comment by jameelbrochu** [comment]
Perfect! I think we will probably need to re-increase the height of the calendar so that all the details fit. I'll look into it.

**Comment by jameelbrochu** [comment]
Small bug: In the popup, it shows LEC and TUT instead of Lecture and Tutorial.

**Comment by mukulikadey** [comment]
This issue can be closed. When the user clicks on an event on the schedule, a modal popup appears with all the course details, also allowing the user to input text for adding course descriptions.

**Comment by jameelbrochu** [comment]
Time: 3 hours
